# For details on buf.yaml configuration, visit https://buf.build/docs/configuration/v2/buf-yaml
version: v2
plugins:
  - local: protoc-gen-openapi
    out: .
    strategy: all
    opt:
      - fq_schema_naming=true
      - default_response=false
      - title=Controller Service
      - version=v1
      - description=This is the OpenAPI schema for Controller gRPC API
      - naming=json
