name: Build Go Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '26'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: make install-tools
      - name: Lint
        run: make lint
      - name: Build
        run: make
      - name: Test
        run: make test
      - name: Vulncheck
        run: make vulncheck
